podtato-head:
  fullnameOverride: podtatohead
  # applies to all deployments in this chart
  replicaCount: 0
  entry:
    serviceType: ClusterIP

  # applies to podtato-head-entry deployment only
  ingress:
    enabled: true
    #className: "traefik"
    className: "nginx"
    hosts:
      #- host: podtatohead-prod.k3s.fritz.box
      - host: podtatohead-prod.k8s.abalulu.de
        paths: 
          - path: /
            #pathType: ImplementationSpecific
            pathType: Prefix